---

- name: NINGHAO PLAYBOOK | by ninghao.net
  hosts: all
  sudo: true

  # 自定义变量

  vars:
    Repo:
      epel: epel-release-7-5.noarch.rpm
      ius: ius-release-1.0-13.ius.centos7.noarch.rpm
    App:
      user: vagrant

  vars_files:
    - config/dev/git.yml
    - config/dev/drupal.yml
    - config/dev/mariadb.yml
    - config/dev/phpmyadmin.yml

  # Roles

  roles:
    - role: init
      tags: init
    - role: php-fpm
      tags: php-fpm
    - role: tool
      tags: tool
    - role: nginx
      tags: nginx
    - role: mariadb
      tags: mariadb
    - role: drupal
      tags: drupal
    - role: drupal_contrib
      tags: drupal_contrib
    - role: phpmyadmin
      tags: phpmyadmin

  handlers:
    - name: 重启 nginx
      service: name=nginx state=restarted
    - name: 重启 php-fpm
      service: name=php-fpm state=restarted
    - name: 重启 mariadb
      service: name=mariadb state=restarted
    - name: 刷新模块的翻译
      command: /usr/bin/drush l10n-update-refresh chdir={{ Drupal.root }}
    - name: 更新模块的翻译
      command: /usr/bin/drush l10n-update chdir={{ Drupal.root }}
